version: '2'
# Build a data volume container with the chef cookbooks on it.
services:
  my-mongo:
    build: ./my-mongo
  my-node-db:
    build: ./my-node-db
    ports:
      - "27017:27017"
    volumes_from:
      - "my-mongo"
  my-node-app:
    build: ./my-node-app
    ports:
      - "3000:3000"
    links:
      - "my-node-api"
    depends_on:
      - "my-node-api"
  my-node-api:
    build: ./my-node-app
    ports:
      - "3001:3000"
    links:
      - "my-node-db"
    depends_on:
      - "my-node-db"
