version: '2'
# Build a data volume container with the chef cookbooks on it.
services:
  my-mongo:
    build: ./my-mongo
  my-node-db:
    build: ./my-node-db
    volumes_from:
      - "my-mongo"
  my-node-app:
    build: ./my-node-app
    ports:
      - "3000:3000"
    links:
      - "my-node-api"
    depends_on:
      - "my-node-api"
    environment:
      - API_URL=$API_URL
      - PORT=3000
  my-node-api:
    build: ./my-node-app
    ports:
      - 3001:3001
    links:
      - "my-node-db"
    depends_on:
      - "my-node-db"
    environment:
      - DB_URL=mongodb://my-node-db/poker
      - PORT=3001
